### ISSUE TITLE
List of curently available skills

### ISSUE THREAD

**Issue by ethanaward** [MycroftAI/mycroft-core-documentation#16]
There should be a list of all the currently available skills, and how to trigger them.

**Comment by ryanleesipes** [comment]
Agreed, this is an older version: https://mycroft.ai/skills

**Comment by ethanaward** [comment]
This should be solved by #20. I listed all of the skills that I know are working, including multiple test cases if there were multiple intents in the skill.

**Comment by ryanleesipes** [comment]
Excellent, closing this issue.
