### ISSUE TITLE
Breakdown of different components of Mycroft Core

### ISSUE THREAD

**Issue by ryanleesipes** [MycroftAI/mycroft-core-documentation#2]
We should detail the different parts of Mycroft Core:

- Messagebus Service
- Skills Service
- Voice Service
- CLI Service
- Enclosure Service (Optional, but should be detailed)

**Comment by Wolfgange3311999** [comment]
Are you looking for something like the "Mycroft Core Introduction" wiki
page on the old repo or something with more emphasis on what
responsibilities each service has?

**Comment by ryanleesipes** [comment]
Responsibilities of each service, so that someone can wrap their head
around everything.

On Sat, May 21, 2016, 11:35 AM Matthew D. Scholefield <
notifications@github.com> wrote:

> Are you looking for something like the "Mycroft Core Introduction" wiki
> page on the old repo or something with more emphasis on what
> responsibilities each service has?
>
> On Fri, May 20, 2016, 4:23 PM Ryan Sipes <notifications@github.com> wrote:
>
> > We should detail the different parts of Mycroft Core:
> >
> > - Messagebus Service
> > - Skills Service
> > - Voice Service
> > - CLI Service
> > - Enclosure Service (Optional, but should be detailed)
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/MycroftAI/mycroft-core-documentation/issues/2>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MycroftAI/mycroft-core-documentation/issues/2#issuecomment-220787440>
>
-- 
Ryan Sipes
CTO, Mycroft A.I.
https://mycroft.ai
785-979-6091

**Comment by ethanaward** [comment]
Who would be the best people to talk with about each of these services? Presumably @jdorleans for the enclosure code, or possibly @isaacnward if he feels like he understands it enough. What about for the other parts of the core?

**Comment by ryanleesipes** [comment]
Don't worry about detailing the enclosure stuff. That is not a true part of Mycroft Core. However, the skills service, messagebus service, cli service, and voice service are. @jdorleans is a good resource for this. @clusterfudge is also a good resource. @Wolfgange3311999 understands quite a lot about the voice service, so perhaps he can collaborate with you on this.
