### ISSUE TITLE
Reference to defaults.ini

### ISSUE THREAD

**Issue by the7erm** [MycroftAI/mycroft-core-documentation#24]
https://github.com/MycroftAI/mycroft-core-documentation/blob/master/user/pages/02.development/docs.md#configuration
> - `defaults.ini`, which lives inside the mycroft codebase/distribution

This file/folder doesn't exist in [mycroft-core](https://github.com/MycroftAI/mycroft-core/tree/master/mycroft).
However [mycroft/configuration/mycroft.ini](https://github.com/MycroftAI/mycroft-core/tree/master/mycroft/configuration)  does.
Should it be `mycroft.ini` or are we missing `codebase/distribution` in [mycroft-core](https://github.com/MycroftAI/mycroft-core)?

**Comment by ethanaward** [comment]
Fixed by #25, closing.
