### ISSUE TITLE
How to Contribute to Mycroft-Core

### ISSUE THREAD

**Issue by ryanleesipes** [MycroftAI/mycroft-core-documentation#6]
A page should include where the Repo is at, a link to the Contributing.md doc, a link to join the Slack channel, and where the forums are at. And should encourage people to contribute (with fancy language).

**Comment by ethanaward** [comment]
For Contributing.md, would it be better to have a link to the page on the repo (https://github.com/MycroftAI/mycroft-core/blob/master/CONTRIBUTING.md), or just include its contents inside this new page about how to contribute?

**Comment by ethanaward** [comment]
Also, at the moment, it looks like the Slack channel requires an @mycroft.ai email address in order for you to create an account without being invited. I don't think that'll work with just a link to the Slack channel in the documentation.

**Comment by ryanleesipes** [comment]
Great, closing this, solved by #9
