### ISSUE TITLE
List Required Packages.

### ISSUE THREAD

**Issue by ryanleesipes** [MycroftAI/mycroft-core-documentation#7]
In build_host_setup.sh all the packages needed are listed, we need to figure out their proper name and list them as dependencies (for setting up the development environment) in the docs.

**Comment by ethanaward** [comment]
I ran through all of the packages listed in build_host_setup.sh with `sudo apt-get changelog <package>`, which gave me this list. Is this what we need? If so, do we need to find non-ubuntu specific versions of those that have specific ubuntu versions to support more versions of linux?
`git 1:2.7.4-0ubuntu1`
`python-defaults 2.7.11-1` (for both python and python-dev in build_host_setup.sh)
`python-setuptools 20.7.0-1`
`python-virtualenv 15.0.1+ds-3`
`pygobject 3.20.0-0ubuntu1`
`virtualenvwrapper 4.3.1-2`
`libtool 2.4.6-0.1`
`libffi 3.2.1-4`
`openssl 1.0.2g-1ubuntu4.1`
`autoconf 2.69-9`
`bison 2:3.0.4.dfsg-1`
`swig 3.0.8-0ubuntu3`
`glib2.0 2.48.0-1ubuntu4`
`s3cmd 1.6.1-1`
`portaudio19 19+svn20140130-1build1`
`mpg123 1.22.4-1`

**Comment by ryanleesipes** [comment]
Yeah, that is pretty much what we need. Not sure that the exact versions are necessary (except for python2, since I don't think Mycroft supports Python3 yet).

**Comment by ethanaward** [comment]
Do we just need the versions up to the latest version then, i.e. python-setuptools 20? Or would python-setuptools be sufficient?

**Comment by ryanleesipes** [comment]
It's fine. Python 2 is only requirement.

On Tue, May 31, 2016, 5:11 PM Ethan Ward <notifications@github.com> wrote:

> Do we just need the versions up to the latest version then, i.e.
> python-setuptools 20? Or would python-setuptools be sufficient?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MycroftAI/mycroft-core-documentation/issues/7#issuecomment-222837054>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACCttfzFFzyGszpPB8qPIwn9OrKTyjAzks5qHLItgaJpZM4Iq0aH>
> .
>
-- 
Ryan Sipes
CTO, Mycroft A.I.
https://mycroft.ai
785-979-6091
